repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: requirements-txt-fixer

  - repo: https://github.com/sqlfluff/sqlfluff
    rev: "2.3.1"
    hooks:
      - id: sqlfluff-lint
        entry: sqlfluff lint --processes 0
        description: "Lints sql files with `SQLFluff`"
        types: [sql]
        additional_dependencies:
          ["dbt-metricflow[snowflake]~=0.2.0", "sqlfluff-templater-dbt~=2.3.1"]
      - id: sqlfluff-fix
        entry: sqlfluff fix --force --show-lint-violations --processes 0
        description: "Fixes sql lint errors with `SQLFluff`"
        types: [sql]
        additional_dependencies:
          ["dbt-metricflow[snowflake]~=0.2.0", "sqlfluff-templater-dbt~=2.3.1"]