name: "jaffle_shop"
version: "2.1.0"
config-version: 2
dbt-cloud:
  project-id: "318162"
  account-name: "dbt Labs - ProServ Sandbox"
  account-id: "51798"
  
profile: "snowflake"
require-dbt-version: ">=1.6.0"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["jaffle-data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  truncate_timespan_to: "{{ current_timestamp() }}"
  "dbt_date:time_zone": "America/Los_Angeles"
  full_test: true
  is_full_test: false


seeds:
  jaffle_shop:
    +schema: jaffle_shop_raw

models:
  jaffle_shop:
    staging:
      +materialized: view
    marts:
      +materialized: table
      jkumalah_customers:
        +schema: jkumalah_customers

  elementary:
    +schema: elementary
